### ISSUE TITLE
I'm not able to open this website 

### ISSUE THREAD

**Issue by suraj-83** [princechamp07/PortFolio#1]
![Screenshot 2024-03-10 001933](https://github.com/princechamp07/PortFolio/assets/159002432/d06c994b-084c-4013-aa5c-10575bc11d11)

**Comment by princechamp07** [comment]
> ![Screenshot 2024-03-10 001933](https://private-user-images.githubusercontent.com/159002432/311461375-d06c994b-084c-4013-aa5c-10575bc11d11.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNDQ4MDMsIm5iZiI6MTcxMDA0NDUwMywicGF0aCI6Ii8xNTkwMDI0MzIvMzExNDYxMzc1LWQwNmM5OTRiLTA4NGMtNDAxMy1hYTVjLTEwNTc1YmMxMWQxMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMFQwNDIxNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNWY0ZmRmODJkNGFhNTYwZTg2OGQ1MDdkZTE1OWU2NzgwNTU1ZTMyYWNmYTZkYzc2NWIzZTdiZDZmZmM1ZjBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rNC6kcNTBQxTSpGtVz_Vlm-hyXRiT4pxE10reEeLEbA)

Try clicking on detail and click allow visit this unsafe website for once.

**Comment by suraj-83** [comment]
now all set 👍
